import { useEffect, useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { BookHeart, Brain, Check, ChevronRight, Clock3, Headphones, HeartHandshake, Map, MessageCircleHeart, Play, RotateCcw, Save, Share2, Sparkles, Star, Volume2 } from 'lucide-react';
import PageLayout from '@/components/PageLayout';
import { useTranslation } from '@/hooks/useTranslation';
import { contentData, type ContentItem } from '@/lib/contentData';
import { copyText, shareContent } from '@/lib/shareService';

type Lang = 'ar' | 'en' | 'fr' | 'es' | 'tr' | 'id';
type Tab = 'journey' | 'situations' | 'journal' | 'map' | 'memory' | 'coach' | 'family';

const ui: Record<Lang, Record<string, string>> = {
  ar: { title: 'رحلتي مع السنة', subtitle: 'عادات صغيرة، أثر كبير', today: 'سنة اليوم', done: 'أتممتها', start: 'ابدأ الآن', journey: 'رحلتي', situations: 'حسب الموقف', journal: 'تأملاتي', map: 'خريطة السنة', coach: 'المساعد الموثوق', family: 'العائلة', note: 'ماذا شعرت بعد التطبيق؟', save: 'حفظ التأمل', saved: 'تم الحفظ', source: 'المصدر', practice: 'طريقة التطبيق', choose: 'اختر موقفاً', coachTitle: 'اسأل عن ممارسة عملية', coachHint: 'مثال: ماذا أفعل عندما أغضب؟', ask: 'إجابة موثقة', familyTitle: 'تحدي العائلة الخاص', familyHint: 'اكتب تحدياً بسيطاً لأفراد الأسرة', add: 'إضافة التحدي', memory: 'مراجعة محفوظاتك', completed: 'مكتمل', share: 'مشاركة', listen: 'استماع', pause: 'إيقاف', streak: 'أيام متتالية', remaining: 'متبقي', days: 'أيام', verifiedCollection: 'مجموعة موثقة', reviewedCollection: 'مجموعة مراجعة', coachDisclaimer: 'تستخدم الإجابات فئات راجعها التطبيق وليست فتاوى.', choosePath: 'اختر مساراً لمدة 7 أيام', reset: 'إعادة ضبط' },
  en: { title: 'My Sunnah Journey', subtitle: 'Small practices, lasting impact', today: 'Sunnah of the moment', done: 'I practised it', start: 'Start now', journey: 'Journey', situations: 'By situation', journal: 'Reflections', map: 'Sunnah map', coach: 'Trusted coach', family: 'Family', note: 'How did you feel after practising?', save: 'Save reflection', saved: 'Saved', source: 'Source', practice: 'How to practise', choose: 'Choose a situation', coachTitle: 'Ask for a practical practice', coachHint: 'Example: What can I do when I feel angry?', ask: 'Source-based answer', familyTitle: 'Private family challenge', familyHint: 'Write a simple challenge for your family', add: 'Add challenge', memory: 'Review your saved practices', completed: 'Completed', share: 'Share', listen: 'Listen', pause: 'Pause', streak: 'day streak', remaining: 'remaining', days: 'days', verifiedCollection: 'Verified collection', reviewedCollection: 'Reviewed collection', coachDisclaimer: 'Answers use the app’s reviewed categories and are not fatwas.', choosePath: 'Choose a 7-day path', reset: 'Reset' },
  fr: { title: 'Mon parcours Sunnah', subtitle: 'De petites pratiques, un grand impact', today: 'La Sunnah du moment', done: "Je l'ai pratiquée", start: 'Commencer', journey: 'Parcours', situations: 'Par situation', journal: 'Réflexions', map: 'Carte Sunnah', coach: 'Coach fiable', family: 'Famille', note: 'Comment vous êtes-vous senti après ?', save: 'Enregistrer', saved: 'Enregistré', source: 'Source', practice: 'Comment la pratiquer', choose: 'Choisir une situation', coachTitle: 'Demander une pratique concrète', coachHint: 'Exemple : que faire quand je suis en colère ?', ask: 'Réponse sourcée', familyTitle: 'Défi familial privé', familyHint: 'Écrivez un petit défi familial', add: 'Ajouter le défi', memory: 'Réviser vos pratiques', completed: 'Terminé', share: 'Partager', listen: 'Écouter', pause: 'Pause', streak: 'jours consécutifs', remaining: 'restant', days: 'jours', verifiedCollection: 'Collection vérifiée', reviewedCollection: 'Collection révisée', coachDisclaimer: 'Les réponses utilisent des catégories révisées et ne sont pas des fatwas.', choosePath: 'Choisissez un parcours de 7 jours', reset: 'Réinitialiser' },
  es: { title: 'Mi camino Sunnah', subtitle: 'Pequeñas prácticas, gran impacto', today: 'La Sunnah del momento', done: 'La practiqué', start: 'Comenzar', journey: 'Camino', situations: 'Por situación', journal: 'Reflexiones', map: 'Mapa Sunnah', coach: 'Guía fiable', family: 'Familia', note: '¿Cómo te sentiste después?', save: 'Guardar', saved: 'Guardado', source: 'Fuente', practice: 'Cómo practicarla', choose: 'Elegir situación', coachTitle: 'Pedir una práctica concreta', coachHint: 'Ejemplo: ¿qué hago cuando me enfado?', ask: 'Respuesta con fuente', familyTitle: 'Reto familiar privado', familyHint: 'Escribe un reto sencillo', add: 'Añadir reto', memory: 'Repasar prácticas', completed: 'Completado', share: 'Compartir', listen: 'Escuchar', pause: 'Pausa', streak: 'días seguidos', remaining: 'restantes', days: 'días', verifiedCollection: 'Colección verificada', reviewedCollection: 'Colección revisada', coachDisclaimer: 'Las respuestas usan categorías revisadas y no son fatwas.', choosePath: 'Elige un camino de 7 días', reset: 'Restablecer' },
  tr: { title: 'Sünnet Yolculuğum', subtitle: 'Küçük uygulamalar, kalıcı etki', today: 'Anın sünneti', done: 'Uyguladım', start: 'Başla', journey: 'Yolculuk', situations: 'Duruma göre', journal: 'Düşünceler', map: 'Sünnet haritası', coach: 'Güvenilir rehber', family: 'Aile', note: 'Uyguladıktan sonra nasıl hissettin?', save: 'Kaydet', saved: 'Kaydedildi', source: 'Kaynak', practice: 'Nasıl uygulanır', choose: 'Bir durum seç', coachTitle: 'Pratik bir uygulama sor', coachHint: 'Örnek: Öfkelendiğimde ne yapabilirim?', ask: 'Kaynaklı cevap', familyTitle: 'Özel aile meydan okuması', familyHint: 'Ailen için basit bir görev yaz', add: 'Görevi ekle', memory: 'Kayıtlarını gözden geçir', completed: 'Tamamlandı', share: 'Paylaş', listen: 'Dinle', pause: 'Duraklat', streak: 'günlük seri', remaining: 'kaldı', days: 'gün', verifiedCollection: 'Doğrulanmış koleksiyon', reviewedCollection: 'İncelenmiş koleksiyon', coachDisclaimer: 'Yanıtlar uygulamanın incelenmiş kategorilerini kullanır ve fetva değildir.', choosePath: '7 günlük bir yol seç', reset: 'Sıfırla' },
  id: { title: 'Perjalanan Sunnah Saya', subtitle: 'Amalan kecil, dampak besar', today: 'Sunnah saat ini', done: 'Sudah diamalkan', start: 'Mulai', journey: 'Perjalanan', situations: 'Menurut situasi', journal: 'Refleksi', map: 'Peta Sunnah', coach: 'Pembimbing tepercaya', family: 'Keluarga', note: 'Bagaimana perasaanmu setelah mengamalkannya?', save: 'Simpan', saved: 'Tersimpan', source: 'Sumber', practice: 'Cara mengamalkan', choose: 'Pilih situasi', coachTitle: 'Tanyakan amalan praktis', coachHint: 'Contoh: Apa yang dilakukan saat marah?', ask: 'Jawaban bersumber', familyTitle: 'Tantangan keluarga pribadi', familyHint: 'Tulis tantangan sederhana', add: 'Tambah tantangan', memory: 'Tinjau amalan tersimpan', completed: 'Selesai', share: 'Bagikan', listen: 'Dengarkan', pause: 'Jeda', streak: 'hari beruntun', remaining: 'tersisa', days: 'hari', verifiedCollection: 'Koleksi tepercaya', reviewedCollection: 'Koleksi yang ditinjau', coachDisclaimer: 'Jawaban menggunakan kategori yang ditinjau aplikasi dan bukan fatwa.', choosePath: 'Pilih perjalanan 7 hari', reset: 'Atur ulang' },
};

const meta: Record<Lang, { day: string; verified: string; explore: string; nodes: Record<string, string> }> = {
  ar: { day: 'اليوم', verified: 'ممارسة موثقة', explore: 'استكشف السنن', nodes: { worship: 'العبادة', character: 'حسن الخلق', family: 'العائلة', health: 'الصحة', food: 'الطعام', community: 'المجتمع' } },
  en: { day: 'Day', verified: 'verified practice', explore: 'Explore practices', nodes: { worship: 'Worship', character: 'Character', family: 'Family', health: 'Health', food: 'Food', community: 'Community' } },
  fr: { day: 'Jour', verified: 'pratique vérifiée', explore: 'Découvrir les pratiques', nodes: { worship: 'Adoration', character: 'Caractère', family: 'Famille', health: 'Santé', food: 'Alimentation', community: 'Communauté' } },
  es: { day: 'Día', verified: 'práctica verificada', explore: 'Explorar prácticas', nodes: { worship: 'Adoración', character: 'Carácter', family: 'Familia', health: 'Salud', food: 'Alimentación', community: 'Comunidad' } },
  tr: { day: 'Gün', verified: 'doğrulanmış uygulama', explore: 'Uygulamaları keşfet', nodes: { worship: 'İbadet', character: 'Ahlak', family: 'Aile', health: 'Sağlık', food: 'Yemek', community: 'Toplum' } },
  id: { day: 'Hari', verified: 'amalan tepercaya', explore: 'Jelajahi amalan', nodes: { worship: 'Ibadah', character: 'Akhlak', family: 'Keluarga', health: 'Kesehatan', food: 'Makanan', community: 'Masyarakat' } },
};

const situations: Record<string, { icon: string; title: Record<Lang, string>; category: string; advice: Record<Lang, string> }> = {
  anger: { icon: '🌿', category: 'advices', title: { ar: 'عندما أغضب', en: 'When I feel angry', fr: 'Quand je suis en colère', es: 'Cuando me enfado', tr: 'Öfkelendiğimde', id: 'Saat marah' }, advice: { ar: 'استعذ بالله، غيّر وضعك واجعل كلامك أطيب.', en: 'Seek refuge in Allah, change your posture and choose kinder words.', fr: 'Cherchez refuge auprès d’Allah, changez de posture et choisissez des mots plus doux.', es: 'Busca refugio en Allah, cambia de postura y elige palabras amables.', tr: 'Allah’a sığın, pozisyonunu değiştir ve daha güzel sözler seç.', id: 'Memohon perlindungan Allah, ubah posisi dan pilih kata yang lebih baik.' } },
  sleep: { icon: '🌙', category: 'sleepAdhkar', title: { ar: 'قبل النوم', en: 'Before sleep', fr: 'Avant de dormir', es: 'Antes de dormir', tr: 'Uyumadan önce', id: 'Sebelum tidur' }, advice: { ar: 'اقرأ أذكار النوم بهدوء واترك هاتفك قبل النوم.', en: 'Read the sleep adhkar calmly and put your phone away.', fr: 'Lisez les adhkar du sommeil calmement et éloignez votre téléphone.', es: 'Lee los adhkar del sueño con calma y deja el teléfono.', tr: 'Uyku zikirlerini sakince oku ve telefonu bırak.', id: 'Baca zikir sebelum tidur dengan tenang dan jauhkan ponsel.' } },
  gratitude: { icon: '✨', category: 'dailySonan', title: { ar: 'عندما أشعر بالامتنان', en: 'When I feel grateful', fr: 'Quand je ressens de la gratitude', es: 'Cuando siento gratitud', tr: 'Şükrettiğimde', id: 'Saat bersyukur' }, advice: { ar: 'احمد الله وشارك نعمتك بكلمة طيبة أو صدقة.', en: 'Praise Allah and express the blessing through kind words or charity.', fr: 'Louez Allah et exprimez cette grâce par une parole douce ou une aumône.', es: 'Alaba a Allah y expresa la bendición con una palabra amable o caridad.', tr: 'Allah’a hamdet ve nimeti güzel söz veya sadakayla paylaş.', id: 'Pujilah Allah dan ungkapkan nikmat dengan kata baik atau sedekah.' } },
  family: { icon: '🤝', category: 'wifeTips', title: { ar: 'مع عائلتي', en: 'With my family', fr: 'Avec ma famille', es: 'Con mi familia', tr: 'Ailemle', id: 'Bersama keluarga' }, advice: { ar: 'ابدأ بالسلام والابتسامة والكلمة الطيبة.', en: 'Begin with salam, a smile and a kind word.', fr: 'Commencez par le salut, un sourire et une parole bienveillante.', es: 'Comienza con el saludo, una sonrisa y una palabra amable.', tr: 'Selam, gülümseme ve güzel bir sözle başla.', id: 'Mulailah dengan salam, senyuman dan kata yang baik.' } },
};

const paths = [
  { id: 'character', icon: '🌱', title: { ar: 'حسن الخلق', en: 'Beautiful character', fr: 'Beau caractère', es: 'Buen carácter', tr: 'Güzel ahlak', id: 'Akhlak mulia' } },
  { id: 'morning', icon: '🌅', title: { ar: 'صباح هادئ', en: 'Peaceful mornings', fr: 'Matins paisibles', es: 'Mañanas tranquilas', tr: 'Huzurlu sabahlar', id: 'Pagi yang tenang' } },
  { id: 'family', icon: '💛', title: { ar: 'دفء العائلة', en: 'Family kindness', fr: 'Bonté en famille', es: 'Bondad familiar', tr: 'Aile sevgisi', id: 'Kebaikan keluarga' } },
];

function allContent(): ContentItem[] { return Object.values(contentData).flat() as ContentItem[]; }
function readCompleted(): string[] { try { const value = JSON.parse(localStorage.getItem('companion_completed') || '[]'); return Array.isArray(value) ? value.filter((item): item is string => typeof item === 'string') : []; } catch { return []; } }

export default function Companion() {
  const { language } = useTranslation();
  const lang = (language in ui ? language : 'en') as Lang;
  const t = (key: string) => ui[lang][key] ?? ui.en[key] ?? key;
  const [tab, setTab] = useState<Tab>('journey');
  const [completed, setCompleted] = useState<string[]>(readCompleted);
  const [note, setNote] = useState(() => localStorage.getItem('companion_note') || '');
  const [saved, setSaved] = useState(false);
  const [familyChallenge, setFamilyChallenge] = useState(() => localStorage.getItem('family_challenge') || '');
  const [familyInput, setFamilyInput] = useState('');
  const [coachQuestion, setCoachQuestion] = useState('');
  const [coachAnswer, setCoachAnswer] = useState('');
  const [playing, setPlaying] = useState(false);

  const items = useMemo(() => allContent(), []);
  const today = items[new Date().getDate() % Math.max(items.length, 1)];
  const streak = completed.length;
  const toggleCompleted = (id: string) => setCompleted((current) => {
    const next = current.includes(id) ? current.filter((item) => item !== id) : [...current, id];
    localStorage.setItem('companion_completed', JSON.stringify(next));
    return next;
  });
  const saveNote = () => { localStorage.setItem('companion_note', note); setSaved(true); window.setTimeout(() => setSaved(false), 1600); };
  const speak = () => {
    if (!('speechSynthesis' in window) || !today) return;
    if (playing) { window.speechSynthesis.cancel(); setPlaying(false); return; }
    const utterance = new SpeechSynthesisUtterance(`${today.arabic}. ${today.transliteration || ''}`);
    utterance.lang = ({ ar: 'ar-SA', en: 'en-US', fr: 'fr-FR', es: 'es-ES', tr: 'tr-TR', id: 'id-ID' } as Record<Lang, string>)[lang]; utterance.rate = 0.82;
    utterance.onend = () => setPlaying(false); window.speechSynthesis.speak(utterance); setPlaying(true);
  };
  const shareToday = () => today && shareContent({ title: t('today'), text: `${today.arabic}\n\n${today.source || ''}`, url: `${window.location.origin}/companion` });
  const addFamily = () => { if (familyInput.trim()) { localStorage.setItem('family_challenge', familyInput.trim()); setFamilyChallenge(familyInput.trim()); setFamilyInput(''); } };
  const askCoach = () => {
    const q = coachQuestion.toLowerCase();
    const found = q.includes('anger') || q.includes('angry') || q.includes('colère') || q.includes('غضب') ? situations.anger : q.includes('sleep') || q.includes('dorm') || q.includes('نوم') ? situations.sleep : situations.gratitude;
    setCoachAnswer(`${found.advice[lang]}\n\n${t('source')}: ${found.category}. This is practical guidance, not a religious ruling. Please verify detailed questions with a qualified scholar.`);
  };

  const tabs: Array<[Tab, React.ReactNode, string]> = [
    ['journey', <Sparkles className="w-4 h-4" />, t('journey')], ['situations', <HeartHandshake className="w-4 h-4" />, t('situations')], ['journal', <BookHeart className="w-4 h-4" />, t('journal')], ['map', <Map className="w-4 h-4" />, t('map')], ['memory', <Clock3 className="w-4 h-4" />, t('memory')], ['coach', <MessageCircleHeart className="w-4 h-4" />, t('coach')], ['family', <Star className="w-4 h-4" />, t('family')],
  ];

  return <PageLayout title={t('title')} subtitle={t('subtitle')}>
    <div className="max-w-3xl mx-auto px-4 pb-24 space-y-5" dir={lang === 'ar' ? 'rtl' : 'ltr'}>
      <section className="rounded-3xl p-5" style={{ background: 'linear-gradient(135deg,var(--gold-muted-strong),var(--teal-muted))', border: '1px solid var(--gold-border-strong)' }}>
        <div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold" style={{ color: 'var(--text-gold)' }}>{t('today')}</p><h2 className="amiri text-2xl font-bold mt-2" style={{ color: 'var(--text-primary)' }}>{today?.arabic}</h2><p className="text-xs mt-2" style={{ color: 'var(--text-muted)' }}>📚 {today?.source || t('verifiedCollection')}</p></div><div className="flex gap-2"><button onClick={speak} className="p-2.5 rounded-xl" style={{ background: 'var(--teal-muted-strong)', color: 'var(--text-teal)' }} aria-label={playing ? t('pause') : t('listen')}>{playing ? <Volume2 className="w-5 h-5" /> : <Headphones className="w-5 h-5" />}</button><button onClick={() => void shareToday()} className="p-2.5 rounded-xl" style={{ background: 'var(--gold-muted-strong)', color: 'var(--text-gold)' }} aria-label={t('share')}><Share2 className="w-5 h-5" /></button></div></div>
        <button onClick={() => today && toggleCompleted(today.id)} className="mt-4 w-full py-3 rounded-xl font-bold flex items-center justify-center gap-2" style={{ background: completed.includes(today?.id || '') ? 'var(--teal-muted-strong)' : 'var(--gold-muted-strong)', color: completed.includes(today?.id || '') ? 'var(--text-teal)' : 'var(--text-gold)', border: '1px solid var(--gold-border)' }}>{completed.includes(today?.id || '') ? <Check className="w-4 h-4" /> : <Sparkles className="w-4 h-4" />}{completed.includes(today?.id || '') ? t('completed') : t('done')}</button>
      </section>

      <div className="grid grid-cols-3 gap-2"><div className="rounded-2xl p-3 text-center" style={{ background: 'hsl(var(--card))', border: '1px solid var(--gold-border)' }}><p className="text-2xl font-black" style={{ color: 'var(--text-gold)' }}>{streak}</p><p className="text-[10px]" style={{ color: 'var(--text-muted)' }}>{t('streak')}</p></div><div className="rounded-2xl p-3 text-center" style={{ background: 'hsl(var(--card))', border: '1px solid var(--gold-border)' }}><p className="text-2xl font-black" style={{ color: 'var(--text-teal)' }}>{Math.max(0, 7 - streak)}</p><p className="text-[10px]" style={{ color: 'var(--text-muted)' }}>{t('remaining')}</p></div><div className="rounded-2xl p-3 text-center" style={{ background: 'hsl(var(--card))', border: '1px solid var(--gold-border)' }}><p className="text-2xl font-black" style={{ color: 'var(--text-primary)' }}>7</p><p className="text-[10px]" style={{ color: 'var(--text-muted)' }}>{t('days')}</p></div></div>

      <div className="grid grid-cols-3 sm:grid-cols-6 gap-2 overflow-x-auto pb-1">{tabs.map(([id, icon, label]) => <button key={id} onClick={() => setTab(id)} className="min-w-[82px] flex flex-col items-center gap-1 p-2 rounded-xl text-[10px]" style={{ background: tab === id ? 'var(--gold-muted-strong)' : 'hsl(var(--card))', color: tab === id ? 'var(--text-gold)' : 'var(--text-muted)', border: `1px solid ${tab === id ? 'var(--gold-border-strong)' : 'var(--border-subtle)'}` }}>{icon}{label}</button>)}</div>

      {tab === 'journey' && <section className="space-y-3"><h3 className="font-bold" style={{ color: 'var(--text-primary)' }}>{t('choosePath')}</h3>{paths.map((path, index) => <button key={path.id} onClick={() => toggleCompleted(`path_${path.id}`)} className="w-full flex items-center gap-3 p-4 rounded-2xl text-start" style={{ background: 'hsl(var(--card))', border: '1px solid var(--gold-border)' }}><span className="text-2xl">{path.icon}</span><span className="flex-1"><strong style={{ color: 'var(--text-primary)' }}>{path.title[lang]}</strong><small className="block mt-1" style={{ color: 'var(--text-muted)' }}>{meta[lang].day} {Math.min(index + 1, 7)} · {meta[lang].verified}</small></span>{completed.includes(`path_${path.id}`) ? <Check className="w-5 h-5" style={{ color: 'var(--text-teal)' }} /> : <ChevronRight className="w-5 h-5" style={{ color: 'var(--text-muted)' }} />}</button>)}</section>}

      {tab === 'situations' && <section className="space-y-3"><h3 className="font-bold" style={{ color: 'var(--text-primary)' }}>{t('choose')}</h3>{Object.entries(situations).map(([id, situation]) => <button key={id} onClick={() => setCoachAnswer(`${situation.advice[lang]}\n\n${t('source')}: ${situation.category}`)} className="w-full flex items-center gap-3 p-4 rounded-2xl text-start" style={{ background: 'hsl(var(--card))', border: '1px solid var(--gold-border)' }}><span className="text-2xl">{situation.icon}</span><span className="flex-1"><strong style={{ color: 'var(--text-primary)' }}>{situation.title[lang]}</strong><small className="block mt-1" style={{ color: 'var(--text-muted)' }}>{situation.advice[lang]}</small></span><ChevronRight className="w-5 h-5" style={{ color: 'var(--text-muted)' }} /></button>)}</section>}

      {tab === 'journal' && <section className="rounded-2xl p-4 space-y-3" style={{ background: 'hsl(var(--card))', border: '1px solid var(--gold-border)' }}><div className="flex items-center gap-2"><BookHeart className="w-5 h-5" style={{ color: 'var(--text-teal)' }} /><h3 className="font-bold" style={{ color: 'var(--text-primary)' }}>{t('journal')}</h3></div><textarea value={note} onChange={(event) => setNote(event.target.value)} rows={7} className="w-full rounded-xl p-3 bg-transparent outline-none resize-none" style={{ color: 'var(--text-primary)', border: '1px solid var(--border-default)' }} placeholder={t('note')} /><button onClick={saveNote} className="w-full py-3 rounded-xl flex items-center justify-center gap-2 font-bold" style={{ background: 'var(--teal-muted-strong)', color: 'var(--text-teal)' }}>{saved ? <Check className="w-4 h-4" /> : <Save className="w-4 h-4" />}{saved ? t('saved') : t('save')}</button></section>}

      {tab === 'map' && <section className="grid grid-cols-2 gap-3">{['worship', 'character', 'family', 'health', 'food', 'community'].map((node, index) => <button key={node} onClick={() => toggleCompleted(`map_${node}`)} className="min-h-28 rounded-2xl p-4 text-start" style={{ background: completed.includes(`map_${node}`) ? 'var(--teal-muted-strong)' : 'hsl(var(--card))', border: '1px solid var(--gold-border)' }}><div className="flex items-center justify-between"><Map className="w-5 h-5" style={{ color: index % 2 ? 'var(--text-teal)' : 'var(--text-gold)' }} />{completed.includes(`map_${node}`) && <Check className="w-4 h-4" style={{ color: 'var(--text-teal)' }} />}</div><strong className="block mt-4" style={{ color: 'var(--text-primary)' }}>{meta[lang].nodes[node]}</strong><small style={{ color: 'var(--text-muted)' }}>{meta[lang].explore}</small></button>)}</section>}

      {tab === 'memory' && <section className="space-y-3"><div className="flex items-center justify-between"><h3 className="font-bold" style={{ color: 'var(--text-primary)' }}>{t('memory')}</h3><button onClick={() => { setCompleted([]); localStorage.removeItem('companion_completed'); }} className="text-xs flex items-center gap-1" style={{ color: 'var(--text-muted)' }}><RotateCcw className="w-3 h-3" />{t('reset')}</button></div>{items.filter((item) => completed.includes(item.id)).slice(0, 8).map((item) => <article key={item.id} className="rounded-2xl p-4" style={{ background: 'hsl(var(--card))', border: '1px solid var(--gold-border)' }}><p className="amiri text-xl leading-9" style={{ color: 'var(--text-primary)' }}>{item.arabic}</p><p className="text-xs mt-2" style={{ color: 'var(--text-muted)' }}>{t('source')}: {item.source || t('reviewedCollection')}</p></article>)}{completed.length === 0 && <div className="rounded-2xl p-6 text-center" style={{ background: 'hsl(var(--card))', border: '1px solid var(--border-subtle)', color: 'var(--text-muted)' }}>{t('memory')}</div>}</section>}

      {tab === 'coach' && <section className="rounded-2xl p-4 space-y-3" style={{ background: 'hsl(var(--card))', border: '1px solid var(--gold-border)' }}><div className="flex items-center gap-2"><Brain className="w-5 h-5" style={{ color: 'var(--text-teal)' }} /><h3 className="font-bold" style={{ color: 'var(--text-primary)' }}>{t('coachTitle')}</h3></div><p className="text-xs" style={{ color: 'var(--text-muted)' }}>{t('coachDisclaimer')}</p><input value={coachQuestion} onChange={(event) => setCoachQuestion(event.target.value)} className="w-full rounded-xl p-3 bg-transparent outline-none" style={{ color: 'var(--text-primary)', border: '1px solid var(--border-default)' }} placeholder={t('coachHint')} /><button onClick={askCoach} className="w-full py-3 rounded-xl font-bold" style={{ background: 'var(--gold-muted-strong)', color: 'var(--text-gold)' }}>{t('ask')}</button>{coachAnswer && <div className="whitespace-pre-line rounded-xl p-3 text-sm leading-7" style={{ background: 'var(--teal-muted)', color: 'var(--text-primary)' }}>{coachAnswer}</div>}</section>}

      {tab === 'family' && <section className="rounded-2xl p-4 space-y-3" style={{ background: 'hsl(var(--card))', border: '1px solid var(--gold-border)' }}><div className="flex items-center gap-2"><HeartHandshake className="w-5 h-5" style={{ color: 'var(--text-teal)' }} /><h3 className="font-bold" style={{ color: 'var(--text-primary)' }}>{t('familyTitle')}</h3></div>{familyChallenge && <div className="rounded-xl p-3" style={{ background: 'var(--gold-muted)', color: 'var(--text-primary)' }}>⭐ {familyChallenge}</div>}<input value={familyInput} onChange={(event) => setFamilyInput(event.target.value)} className="w-full rounded-xl p-3 bg-transparent outline-none" style={{ color: 'var(--text-primary)', border: '1px solid var(--border-default)' }} placeholder={t('familyHint')} /><button onClick={addFamily} className="w-full py-3 rounded-xl font-bold" style={{ background: 'var(--teal-muted-strong)', color: 'var(--text-teal)' }}>{t('add')}</button></section>}
    </div>
  </PageLayout>;
}
