/**
 * Translation Service — Google Translate (unofficial, no API key)
 * Used for runtime translation of detail page content.
 * List pages use pre-generated JSON files (see scripts/translate-data.mjs).
 *
 * Cache key: trans_{lang}_{hash32(text)} in localStorage
 */

import type { Language } from '@/lib/translations';

const LANG_MAP: Record<Language, string> = {
  ar: 'ar', en: 'en', fr: 'fr', es: 'es', tr: 'tr', id: 'id',
};

/* ── djb2 hash ─────────────────────────────────────────── */
function hash32(str: string): string {
  let h = 5381;
  for (let i = 0; i < str.length; i++) h = (Math.imul(h, 31) + str.charCodeAt(i)) | 0;
  return (h >>> 0).toString(36);
}

/* ── localStorage cache ────────────────────────────────── */
function fromCache(text: string, lang: Language): string | null {
  try { return localStorage.getItem(`trans_${lang}_${hash32(text)}`); } catch { return null; }
}
function toCache(text: string, lang: Language, val: string): void {
  try { localStorage.setItem(`trans_${lang}_${hash32(text)}`, val); } catch { /* quota */ }
}

/* ── In-flight dedup ───────────────────────────────────── */
const inflight = new Map<string, Promise<string | null>>();

/* ── Google Translate unofficial API ──────────────────── */
async function googleTranslate(text: string, lang: Language): Promise<string | null> {
  if (!text.trim()) return text;
  const url =
    `https://translate.googleapis.com/translate_a/single?client=gtx&sl=ar&tl=${LANG_MAP[lang]}&dt=t&q=` +
    encodeURIComponent(text);
  try {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 8000);
    const r = await fetch(url, {
      headers: { 'User-Agent': 'Mozilla/5.0' },
      signal: controller.signal,
    });
    clearTimeout(timer);
    if (!r.ok) return null;
    const d = await r.json() as Array<Array<Array<string>>>;
    // d[0] = array of sentence chunks [[translatedChunk, originalChunk], ...]
    const translated = (d[0] as Array<[string]>).map(chunk => chunk[0]).join('');
    return translated || null;
  } catch { return null; }
}

/* ── Public: translate one text ────────────────────────── */
export async function translateText(text: string, lang: Language): Promise<string> {
  if (!text || lang === 'ar') return text;
  const cached = fromCache(text, lang);
  if (cached) return cached;

  const key = `${lang}|${hash32(text)}`;
  const pending = inflight.get(key);
  if (pending) return (await pending) ?? text;

  const p = googleTranslate(text, lang);
  inflight.set(key, p);
  try {
    const result = await p;
    if (result) toCache(text, lang, result);
    return result ?? text;
  } finally {
    inflight.delete(key);
  }
}

/* ── Public: translate array ───────────────────────────── */
export async function translateBatch(
  texts: string[],
  lang: Language,
  concurrency = 10,
  onProgress?: (pct: number) => void,
): Promise<string[]> {
  if (lang === 'ar') { onProgress?.(100); return texts; }

  const results = [...texts];
  const todo: Array<{ i: number; text: string }> = [];

  for (let i = 0; i < texts.length; i++) {
    const c = fromCache(texts[i], lang);
    if (c) results[i] = c;
    else if (texts[i]?.trim()) todo.push({ i, text: texts[i] });
  }

  let done = 0;
  const fromCacheCount = texts.length - todo.length;
  onProgress?.(Math.round((fromCacheCount / texts.length) * 100));

  for (let i = 0; i < todo.length; i += concurrency) {
    await Promise.all(
      todo.slice(i, i + concurrency).map(async ({ i: idx, text }) => {
        results[idx] = await translateText(text, lang);
        done++;
        onProgress?.(Math.round(((fromCacheCount + done) / texts.length) * 100));
      })
    );
  }

  onProgress?.(100);
  return results;
}

/* ── Pre-warm cache for all list content ─────────────────
   Called on language switch. Fetches pre-translated JSON
   files (generated by translate-data.mjs), so 0 API calls
   for list content. Detail content is translated on demand.  */
export async function preTranslateAll(
  lang: Language,
  baseUrl: string,
  onProgress?: (pct: number) => void,
): Promise<void> {
  if (lang === 'ar') { onProgress?.(100); return; }
  // Pre-translated static files handle everything — just signal done
  onProgress?.(100);
}

/* ── Cache utilities ───────────────────────────────────── */
export function clearCache(): void {
  try {
    Object.keys(localStorage)
      .filter(k => k.startsWith('trans_'))
      .forEach(k => localStorage.removeItem(k));
  } catch { /**/ }
}
export function clearCacheForLanguage(lang: Language): void {
  try {
    const prefix = `trans_${lang}_`;
    Object.keys(localStorage)
      .filter(k => k.startsWith(prefix))
      .forEach(k => localStorage.removeItem(k));
  } catch { /**/ }
}


export async function batchTranslateText(texts: string[], languages: Language[]): Promise<Array<Record<Language, string>>> {
  const byLanguage = await Promise.all(languages.map(async (language) => [language, await translateBatch(texts, language)] as const));
  return texts.map((_, index) => Object.fromEntries(byLanguage.map(([language, values]) => [language, values[index]])) as Record<Language, string>);
}

export async function translateContentObject<T extends object>(content: T, languages: Language[]): Promise<Record<Language, T>> {
  const translated = {} as Record<Language, T>;
  for (const language of languages) {
    const values = Object.entries(content);
    const strings = values.filter(([, value]) => typeof value === 'string').map(([, value]) => value as string);
    const translatedStrings = await translateBatch(strings, language);
    let stringIndex = 0;
    translated[language] = Object.fromEntries(values.map(([key, value]) => [key, typeof value === 'string' ? translatedStrings[stringIndex++] : value])) as T;
  }
  return translated;
}

export const translationService = {
  translateContent: translateContentObject,
};
